Create ERROR.md
lit-kansai-members/music pull request #269
Opened 2020-11-25 09:15 UTC by mizphses

## 解決するIssue
- close #0
- close #0

## その他関連Issue
- #0
- #0

## その他コメント

2020-11-25 12:37 UTC, AkihiroTokai requested changes
templateを作成していただきありがとうございます。最後にもう一つだけよろしいでしょうか。

2020-11-25 12:37 UTC, AkihiroTokai commented on .github/ISSUE_TEMPLATE/ERROR.md
> +about: "バグ等の報告は子のフォームから行ってください。"
おやおや:eyes:

2020-11-25 13:18 UTC, mizphses commented on .github/ISSUE_TEMPLATE/ERROR.md
> +about: "バグ等の報告は子のフォームから行ってください。"
子供にエラーが起きてるようでしたね。。。

2020-11-26 02:34 UTC, ygkn approved these changes

2020-11-26 03:32 UTC, AkihiroTokai approved these changes

2020-11-27 08:30 UTC, merged