add Spring-2021
lit-kansai-members/music pull request #322
Opened 2021-04-15 09:35 UTC by sugijotaro

## 2021年のスプリングキャンプの曲を追加しました

#追加した曲
・ティーンエイジサンセット
・ココロノナカ

2021-04-15 09:39 UTC, sugijotaro commented
@AkihiroTokai @ren-suke 
確認お願いします！

2021-04-15 14:03 UTC, ren-suke approved these changes

2021-04-15 14:03 UTC, ren-suke commented
@sugijotaro マージOKです！

2021-04-15 14:16 UTC, AkihiroTokai requested changes
PRありがとうございます！説明不足の部分が多くて申し訳ないですがいくつか対応お願いします。

2021-04-15 14:16 UTC, AkihiroTokai commented on index.yml
> +            🎤[DAM] [5238-32](https://www.clubdam.com/karaokesearch/songleaf.html?requestNo=5238-32) [JOYSOUND][843867](https://www.joysound.com/web/search/song/843867)
JOYSOUND のURLと「曲番号」は違うので注意してください。この場合はoriginalのものを優先しているので485874ですね。

2021-04-15 14:16 UTC, AkihiroTokai commented on index.yml
> +            🎤[DAM] [7096-74](https://www.clubdam.com/karaokesearch/songleaf.html?requestNo=7096-74) [JOYSOUND][841935](https://www.joysound.com/web/search/song/841935)
こちらもJOYSOUNDの「曲番号」は485392になります。

2021-04-15 14:16 UTC, AkihiroTokai commented on index.yml
> +            [[歌詞(J-Lyric.net)](https://j-lyric.net/artist/a04ac97/l051b90.html)
[が多くないですか？

2021-04-15 14:25 UTC, AkihiroTokai commented
@sugijotaro .DS_Store はglobalでignoreしておくといいかもしれないですね。#318 と #317 をOpenしていただいた
あやめ@ayame-r 氏のお名前追加もお願いできませんか。
https://qiita.com/takashimelon/items/def769aaaa1d41cc44d4

2021-04-15 14:28 UTC, AkihiroTokai commented
カラオケ番号については #116 のやり取りを参照してください。

2021-04-15 22:38 UTC, sugijotaro commented
了解です！レビューありがとうございます！
学校から帰ったら修正します！

2021-04-16 07:44 UTC, sugijotaro commented
指摘された部分修正しました！確認お願いします！

2021-04-16 10:40 UTC, AkihiroTokai approved these changes
@sugijotaro マジmerge ～

2021-04-16 13:07 UTC, merged