"2021summer~を追加#
lit-kansai-members/music pull request #393
Opened 2022-12-29 18:35 UTC by simasimasimasima

## 解決する Issue

- close #0
- close #0

## その他関連 Issue

- #0　2021夏、冬の背景素材なし、社員さんに相談すればもらえるかも
- 　　テーマ不明の部分あり
- #0

## その他コメント

2023-01-01 08:34 UTC, ren-suke reviewed
@simasimasimasima ちょっとしたフォーマットエラーでCIが落ちちゃってそう！なので、手元で 'yarn format'を実行して再度Pushしてもらえるとapproveできる状態になるかと思います！(エラーとか出たら遠慮なく質問してください)

2023-01-04 15:45 UTC, AkihiroTokai requested changes
ContentsについてReviewしました！記載方法分かりくくてすいません......。

2023-01-04 15:45 UTC, AkihiroTokai commented on index.yml
> +            🎤[DAM] [3914-52](clubdam.com/karaokesearch/songleaf.html?requestNo=3914-52)[JOYSOUND]404 NotFound
https://www.clubdam.com/karaokesearch/songleaf.html?requestNo=3914-52
DAMのURLはこれでお願いします。

2023-01-04 15:45 UTC, AkihiroTokai commented on index.yml
> +            🎤[DAM] [3914-52](clubdam.com/karaokesearch/songleaf.html?requestNo=3914-52)[JOYSOUND]404 NotFound
JOYSOUNDは698510ですね。
https://www.joysound.com/web/search/song/642264

2023-01-04 15:45 UTC, AkihiroTokai commented on index.yml
> +            [YouTube](https://youtu.be/zNOe2fK1hM0)
YouTubeの埋め込みはyoutu.be/contentsIDで

2023-01-04 15:45 UTC, AkihiroTokai commented on index.yml
> +            [歌詞(J-Lyric.net)](https://j-lyric.net/artist/a063b01/l0580da.html)
個別Contentsですがカラオケ（DAM→JOYSOUND）→YouTube→歌詞の順番で記載してください。

2023-01-04 15:45 UTC, AkihiroTokai commented on index.yml
> +            🎤[DAM] [6836-84](https://www.clubdam.com/karaokesearch/songleaf.html?requestNo=6836-84) [JOYSOUND][717059](https://www.joysound.com/web/search/song/905072)
JOYSOUNDのほう486786では？
https://www.joysound.com/web/search/song/850101

2023-01-04 15:45 UTC, AkihiroTokai commented on index.yml
> +            [YouTube]https://youtu.be/AT2tulhSprE)
こちらもyoutu.be/AT2tulhSprEで

2023-01-04 15:45 UTC, AkihiroTokai commented on index.yml
> +            🎤[DAM] [5306-93](https://www.clubdam.com/karaokesearch/songleaf.html?requestNo=6993-21) [JOYSOUND][697374](https://www.joysound.com/web/search/song/615796)
DAMの番号は6993-21ですね。（DAMはURL末尾と一致しているのであわせてご確認ください。）

2023-01-04 15:45 UTC, AkihiroTokai commented on index.yml
> +            🎤[DAM] [5306-93](https://www.clubdam.com/karaokesearch/songleaf.html?requestNo=6993-21) [JOYSOUND][697374](https://www.joysound.com/web/search/song/615796)
JOYSOUNDは494769と以下のURLに修正お願いします。
https://www.joysound.com/web/search/song/905072

2023-01-04 15:45 UTC, AkihiroTokai commented on index.yml
> +            [YouTube](https://youtu.be/pRlzN2I9Knw)
youtu.be/contentsIDにしてほしいのとYouTube→歌詞でお願いします。

2023-01-04 15:45 UTC, AkihiroTokai commented on index.yml
> +            [YouTube](https://youtu.be/qknDI1k39Ic)
youtu.be/contentsIDにしてほしいのとYouTube→歌詞でお願いします。

2023-01-04 15:45 UTC, AkihiroTokai commented on index.yml
> +            🎤[DAM][]https://www.clubdam.com/karaokesearch/songleaf.html?requestNo=5306-93  [JOYSOUND][495717](https://www.joysound.com/web/search/song/897823)
DAMのURLとJOYSOUNDは大丈夫ですがtypoでは？

2023-01-04 15:45 UTC, AkihiroTokai commented on index.yml
> +            🎤[DAM] [5375-18](https://www.clubdam.com/karaokesearch/songleaf.html?requestNo=3914-52) [JOYSOUND][698510](https://www.joysound.com/web/search/song/878603)
DAMのURLご確認ください。
https://www.clubdam.com/karaokesearch/songleaf.html?requestNo=5375-18

2023-01-04 15:45 UTC, AkihiroTokai commented on index.yml
> +            🎤[DAM] [5375-18](https://www.clubdam.com/karaokesearch/songleaf.html?requestNo=3914-52) [JOYSOUND][698510](https://www.joysound.com/web/search/song/878603)
JOYSOUNDは490641かと。

2023-01-04 15:45 UTC, AkihiroTokai commented on index.yml
> +            [YouTube](https://youtu.be/33ZWA1GrrXY)
youtu.be/33ZWA1GrrXYで！

2023-01-04 15:45 UTC, AkihiroTokai commented on index.yml
> +      background: ""
backgroundは指定しないとLiT！ロゴのはずですが、指定できないならここは削除でいいと思います。

2023-01-04 15:45 UTC, AkihiroTokai commented on index.yml
> +            🎤[DAM] [5226-38](https://www.clubdam.com/karaokesearch/songleaf.html?requestNo=5375-18) [JOYSOUND][438157](https://www.joysound.com/web/search/song/745741)
DAMのURLご確認ください。
https://www.clubdam.com/karaokesearch/songleaf.html?requestNo=5226-38

2023-01-04 15:45 UTC, AkihiroTokai commented on index.yml
> +            [YouTube](https://youtu.be/IqrbCSiJCA4)
youtu.be/IqrbCSiJCA4で！

2023-01-04 15:45 UTC, AkihiroTokai commented on index.yml
> +        - title: "しわあわせ"
ママ

2023-01-04 15:45 UTC, AkihiroTokai commented on index.yml
> +
トルツメ

2023-01-04 15:45 UTC, AkihiroTokai commented on index.yml
> +            🎤[DAM] [5351-39](https://www.clubdam.com/karaokesearch/songleaf.html?requestNo=5351-39) [JOYSOUND][716632](https://www.joysound.com/web/search/song/876689)
JOYSOUNDですが本人映像やガイドボーカルではないものを記載している（詳しくはカラオケ番号追加issueを参照）ので490361に変更してください。

2023-01-04 15:45 UTC, AkihiroTokai commented on index.yml
> +            [YouTube](https://youtu.be/JwmGruvGt_I)
youtu.be/JwmGruvGt_Iで！

2024-02-07 16:05 UTC, mizucoffee commented
本PR、重複かと思いますのでCloseさせていただきます。
必要であればReopenください。

2024-02-07 16:05 UTC, closed without merging